### ISSUE TITLE
🐜 Uncaught empty CodeExample error

### ISSUE THREAD

**Issue by JFWooten4** [stellar/stellar-docs#859]
### What version are you using?

`stellar version 11.1.0`

### What did you do?

Create a code example with no content:
```
<CodeExample>

</CodeExample>
```

### What did you expect to see?
× Error: empty CodeExample block at line XYZ.

### What did you see instead?

Unclear error message (full below) or abbreviated to only `Docusaurus error: the <Tabs> component requires at least one <TabItem> children component`

```
Uncaught runtime errors:
× ERROR
Docusaurus error: the <Tabs> component requires at least one <TabItem> children component
    at getInitialStateValue (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:22:1108)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:25:275)
    at mountState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16987:20)
    at Object.useState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17700:16)
    at useState (webpack-internal:///./node_modules/react/cjs/react.development.js:1624:21)
    at useTabs (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:25:270)
    at TabsComponent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Tabs/index.js:20:515)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16306:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20070:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21583:16)
```

**Comment by JFWooten4** [comment]
For anyone wondering, the solution is incorporated:

https://github.com/stellar/stellar-docs/blob/e8416b671eed22652360aeeedf5e69555ac31824/README.md?plain=1#L155
